# Generated by Django 4.2 on 2023-04-09 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreateDatabase', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Treners',
            new_name='Trener',
        ),
        migrations.AlterModelOptions(
            name='trener',
            options={'ordering': ['trener_fio'], 'verbose_name': 'Тренер', 'verbose_name_plural': 'Тренеры'},
        ),
        migrations.RenameField(
            model_name='trener',
            old_name='treners_fio',
            new_name='trener_fio',
        ),
        migrations.RenameField(
            model_name='trener',
            old_name='treners_id',
            new_name='trener_id',
        ),
        migrations.RenameField(
            model_name='trener',
            old_name='treners_kval',
            new_name='trener_kval',
        ),
        migrations.RenameField(
            model_name='trener',
            old_name='treners_passport',
            new_name='trener_passport',
        ),
        migrations.RenameField(
            model_name='trener',
            old_name='treners_team',
            new_name='trener_team',
        ),
    ]
