# Generated by Django 4.2 on 2023-04-29 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreateDatabase', '0002_rename_treners_trener_alter_trener_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trener',
            name='trener_team',
        ),
    ]
