# Generated by Django 4.2 on 2023-04-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateDatabase', '0003_remove_trener_trener_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trener',
            name='trener_passport',
            field=models.TextField(unique=True, verbose_name='Паспорт'),
        ),
    ]
