# Generated by Django 4.2 on 2023-04-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateDatabase', '0005_vidsporta_vidsporta_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_type',
        ),
        migrations.AlterField(
            model_name='vidsporta',
            name='vidsporta_name',
            field=models.TextField(primary_key=True, serialize=False, unique=True, verbose_name='Вид спорта'),
        ),
    ]
