# Generated by Django 4.2 on 2023-04-29 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CreateDatabase', '0007_sportsmen_sportsmen_vidporta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsmen',
            name='sportsmen_vidporta',
            field=models.ForeignKey(default='дзюдо', on_delete=django.db.models.deletion.PROTECT, to='CreateDatabase.vidsporta', verbose_name='Вид спорта'),
        ),
    ]
