# Generated by Django 4.2 on 2023-04-30 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CreateDatabase', '0013_rename_sportsmen_vidporta_sportsmen_sportsmen_vidsporta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsmen',
            name='sportsmen_vidsporta',
            field=models.ForeignKey(db_column='sportsmen_vidsporta', on_delete=django.db.models.deletion.PROTECT, to='CreateDatabase.vidsporta', verbose_name='Вид спорта'),
        ),
    ]
